[theme]
theme = "slick"
[theme.overrides]
idle_bg = "#2e3440" # nord0
idle_fg = "#81a1c1" # light blue
info_bg = "#5e81ac" # dark blue
info_fg = "#2e3440" # nord0
good_bg = "#a3be86" # green
good_fg = "#2e3440" # nord0
warning_bg = "#ebcb8b" # yellow
warning_fg = "#2e3440" # nord0
critical_bg = "#bf616a" # red
critical_fg = "#2e3440" # nord0
separator = ""
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "awesome4"

[icons.overrides]
net_up = "U"
net_down = "D"

[[block]]
block = "focused_window"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "load"
interval = 0.1

[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 1

[[block]]
block = "net"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
format = " $icon $percentage "
