[theme]
name = "bad-wolf"

[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "disk_space"
path = "/home"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MAg} GB"
format_swap = "{SUm} MB"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = " {1m} {5m} {15m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60

format = "%a %d/%m %R"
